### ISSUE TITLE
dcl:cp7, German, and Black Letter/ Gothic Script

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#119]
Anyone good with Black Letter / Gothic typefaces? There's a section in this text ~ https://figgy.princeton.edu/catalog/47d4e27f-1199-403c-9f06-95769f13d3b1 ~ which breaks into German and a very different typeface.

[EDIT: The page in question is image 72 !]

Can someone please suggest an appropriate label for the structmap?

Thanks!

-- David

**Comment by lightgivener** [comment]
Hey David,

I can transcribe / read. Not sure about the appropriate label though. It is an honor homily or similar. I will do some research tomorrow but my German should come in handy ;)

Enjoy the Easter days!

**Comment by lightgivener** [comment]
Alright, image 72 is a sermon about witches and how God saves against them authored by M. Johann. Christoph. Müller a pastor in Witterstat . Couldn't find any info about the sermon, the pastor, or Witterstat and while is it said the pastor wrote this as a favor to his brother in law the overall author Schröter did not have a brother in law with that name.

Image 73 is a short telling of Walpurgis night and St. Walburga (here fashioned as a male) brought forward by the whole 'Tischgesellschaft' (table society - old term meaning a group of organizers since decisions are made at pub meetings). Walpurgis night is the night before first of May when witches meet on the Brocken mountain in Germany (it's a thing), so that fits in with the whole witches bad, God good theme.

below is the transcription of the beginning and end of the pages:


image 72 >> 'frag nicht ob hexen sein und eine solche Rotter 
die stets dem teufel steht durch schafen zu gebother /
[... devils, witches et cetera...]
habt ferner euren Gott im Herzen und vor Augen /
und lasst das rechte Recht in euren dienen taugen /
so [hafft?] zur Straff an euch sein harter Hexen-Knall /
Denn Gott ist euer [Trug?] / Schutz / Segen / Burg und Wall.

Dies anfertigte seinem Vielgeehrten Herrn Schw-
ager aus Bitte aus.

M. Johann. Christoph. Müller

Pastor in Witterstat [?]<<

image 73: >>Walpurgis nacht ist in aller Welt berühmt
[...]
Mit diesen Wenigen [wolec?] des Herrn Walburgers /
gelehrte Schrifft / wohlmeinend beehren
Die sämtliche Tischgesellschaft<<

**Comment by smallfind** [comment]
Excellent. Thanks so much, Charlotte. (And apologies for my delay in replying -- hope you had a good Easter!)

**Comment by smallfind** [comment]
Oh, dear -- Any chance you could take a quick look at the final image? (# 74)

**Comment by lightgivener** [comment]
Apologies, what i trasncribed above as image 73 is of course meant for image 74! image 73 is only the micrifiche header obviously.


correct is:
**image 74:** >>Walpurgis nacht ist in aller Welt berühmt
[...]
Mit diesen Wenigen [wolec?] des Herrn Walburgers /
gelehrte Schrifft / wohlmeinend beehren
Die sämtliche Tischgesellschaft<<

**Comment by smallfind** [comment]
Thank you! :-)
