### ISSUE TITLE
publisher tags

### ISSUE THREAD

**Issue by lmas2019** [pulibrary/cicognara-catalogo#5]
In what way are tagging publishers? I didn't see any previous publisher tags to refer to. So far I've been using <publisher></publisher>, but maybe it would be better to use <pub></pub>

It is possible that I'm missing the standardized tag for this. For some reason I don't get suggestions  like you do when I go to tag something.

**Comment by cwulfman** [comment]
Your tags aren't showing up in the comments; probably because the github interface is swallowing the angle brackets. Try typing them as an ampersand followed by the letters lt and a semicolon for the open angle bracket and gt for the close angle bracket.

So: &lt;publisher&gt;

If you're not getting the autosuggestions, it might because Oxygen still isn't finding the schema.

**Comment by lmas2019** [comment]
Oh I see! &publisher&&/publisher&

That's true. I can't seem to fix this problem of the schema. Would I be able to meet you some time this week to look at it please?

**Comment by jpstroop** [comment]
If it helps, for code samples (and HTML, XML, etc) on Github, surrounding the elements with backticks, e.g.  `<publisher>Hello</publisher>`, or for bigger examples adding three, followed by a newline, followed by three more, e.g.:

```xml
<the>
  <publisher>Hello</publisher>
</the>
```

Will also work, and following the opening backticks with a format hint "xml" in this case will get you syntax highlighting.   

Click the pen to edit this comment to see the source.

**Comment by cwulfman** [comment]
Thank you for reminding us about this, Jon. For others: this is another form of text markup called *Markdown*; it is a good contrast with the sort of markup we are doing with the TEI schema, because it emphasizes layout and rendition over semantics. You can learn about it [here](https://guides.github.com/features/mastering-markdown/); it is very handy!

**Comment by lmas2019** [comment]
Thanks Jon!
